image: maven:3.6.3

clone:
  depth: full
  
pipelines:
  branches:
    master:
      - step:
          name: Heroku Deploy
          caches:
            - node
            - maven
          script:
            - git push --quiet https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD 